### ISSUE TITLE
Force users to fetch latest css file instead of cached

### ISSUE THREAD

**Issue by tibbis** [cloudgrayau/pitch#7]
Hi!

is there a way using your plugin to force users to fetch latest compiled css file instead of cached version? 

I saw some other plugins like Stamp, offering that but I’m not sure it will work together with your plugin.

**Comment by cloudgrayau** [comment]
Hello,

You can also force the users to fetch the latest compiled asset files by using ':DIGIT' in the asset URL prior to the extension, for example 'js/assets/site,plugin/chosen:01.js'. instead of just 'js/assets/site,plugin/chosen.js'.

Whilst in development mode, the browser cache of all assets will be forced to refresh on each page load.

Please let me know how you go.

**Comment by tibbis** [comment]
> Hello,
> 
> You can also force the users to fetch the latest compiled asset files by using ':DIGIT' in the asset URL prior to the extension, for example 'js/assets/site,plugin/chosen:01.js'. instead of just 'js/assets/site,plugin/chosen.js'.
> 
> Whilst in development mode, the browser cache of all assets will be forced to refresh on each page load.
> 
> Please let me know how you go.

ok so it will still work with your plugins cache or advanced caching features? For the digit does your plugin have a build number variable I can access in twig? 

Thanks again!
